cards:
  - path: dev
    title: Hosting and Deployment
    description: Documentation for system administrators who want to run, deploy, maintain and upgrade our publishing software.
    cards:
      - path: admin-guide
        isDeveloper: true
      - path: tech-upgrade-guide
        isDeveloper: true
      - path: release-notebooks
        isDeveloper: true
  - path: dev
    title: Development
    description: Documentation for coders who want to customize our publishing software, write plugins or themes, and make coding contributions.
    cards:
      - path: documentation
        isDeveloper: true
      - path: contributors
        isDeveloper: true
      - path: pkp-theming-guide
        isDeveloper: true
      - path: plugin-guide
        isDeveloper: true
      - path: testing
        isDeveloper: true
  - path: dev
    title: Specifications and Reference Guides
    description: Technical documentation about the REST API, database schema, the UI Library, and application source code.
    cards:
      - path: rest-api
        isDeveloper: true
      - path: database-schema
        isDeveloper: true
      - path: ui-library
        isDeveloper: true
      - path: ojs-reference
        isDeveloper: true
      - path: omp-reference
        isDeveloper: true
  - path: ojs2
    title: Open Journal Systems 2
    description: "Documentation for developers who are still working with OJS 2."
    cards:
        - path: ojs-2-technical-reference
          isDeveloper: true
